version: '3.8'

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    volumes:
      - ./src:/usr/wcf-be/src
    stdin_open: true
    tty: true

volumes:
  db:
